# Generated by Django 3.2.7 on 2021-09-09 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaspoon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order_drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaspoon_app.base_drink')),
                ('topping_id', models.ManyToManyField(to='teaspoon_app.topping')),
            ],
        ),
        migrations.DeleteModel(
            name='drink',
        ),
    ]
