# Generated by Django 3.2.7 on 2021-09-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaspoon_app', '0004_auto_20210911_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('drink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaspoon_app.base_drink')),
            ],
        ),
        migrations.DeleteModel(
            name='order_drink',
        ),
    ]
