# Generated by Django 3.2.7 on 2021-09-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaspoon_app', '0005_auto_20210911_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_drink',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
