# Generated by Django 3.2.7 on 2021-09-14 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaspoon_app', '0006_cart_drink_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart_drink',
            new_name='line_item',
        ),
    ]
