# Generated by Django 3.2.7 on 2021-09-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaspoon_app', '0009_alter_line_item_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_item',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
