# Generated by Django 3.2.7 on 2021-09-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaspoon_app', '0013_order_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='done',
        ),
        migrations.AddField(
            model_name='line_item',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
