# Generated by Django 3.2.7 on 2021-09-17 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaspoon_app', '0014_auto_20210916_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_item',
            name='toppings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teaspoon_app.topping'),
        ),
    ]
