# Generated by Django 3.2.7 on 2021-09-22 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaspoon_app', '0017_alter_base_drink_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='line_item_topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaspoon_app.line_item')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaspoon_app.topping')),
            ],
        ),
    ]
