# Generated by Django 3.2.7 on 2021-09-22 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaspoon_app', '0018_line_item_topping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line_item',
            name='toppings',
        ),
    ]
