# Generated by Django 3.2.7 on 2021-09-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaspoon_app', '0020_auto_20210923_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending_or_dispatched',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
